# Generated by Django 5.1.5 on 2025-02-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering', '0004_remove_order_total_price_food_food_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('Veg', 'Vegetarian'), ('Non-Veg', 'Non-Vegetarian')], default='Veg', max_length=10),
        ),
    ]
