# Generated by Django 5.1.5 on 2025-02-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering', '0005_userprofile_security_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='security_question',
        ),
    ]
